spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yep?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 2017248646
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:*.xml


debug: true
server:
  port: 8088
  ssl:
    key-store: classpath:YEP-Autumn.jks
    key-store-password: a8m602l7midh3
    key-store-type: JKS
