spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yep?useUnicode=true;characterEncoding=utf8;useSSL=true;serverTimezone=GMT%2B8
    username: root
    password: 2017248646
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:*.xml



debug: true
