spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yep?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 2017248646
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:*.xml


server:
  port: 8080
  ssl:
    key-store: classpath:YEP-Autumn.jks
    key-store-password: a8m602l7midh3
    key-store-type: JKS
  servlet:
    context-path: '/EC'

#minio:
#  endpoint: http://23.94.53.48:9090
#  accessKey: YEP
#  secretKey: 2017248646

minio:
  endpoint: http://81.68.81.151:9090
  accessKey: YEP
  secretKey: 2017248646



logging:
  pattern:
    console: "[YEP] %d{HH:mm:ss.SSS} %p [%t] %C.%M(%L) | %m%n"
  level:
    com.netflix.discovery: 'INFO'
    org.springframework.cloud: 'WARN'
